### ISSUE TITLE
What is the purpose of the sample.json file?

### ISSUE THREAD

**Issue by mjfusa** [pnp/copilot-prompts#7]
Sample.json seems to provide metadata regarding the prompt which we provide in the README. Will this be used to populate some kind of prompt directory? Can you share the purpose of this file?
Thanks!

**Comment by arjunumenon** [comment]
Hello @mjfusa  - You are right. The metadata details which will be specified in the sample.json file will be used to show the details about the prompt sample in the [M365 Solution Gallery page](https://adoption.microsoft.com/en-us/sample-solution-gallery/) so that users can quickly search about prompts. Hope that is clear for you. 
Let us know if you have any other questions on the same.

You can also refer [this article](https://devblogs.microsoft.com/microsoft365dev/curating-a-collection-of-free-microsoft-copilot-prompts/) (_Just in case if you have not seen_) which talks about how to use and contribute to the prompt labs repo.

@rabwill  - Please feel free to chime in if I have missed out any other information on this front.

**Comment by mjfusa** [comment]
Thanks @arjunumenon - That makes sense - However the Solutions Gallery as the destination for the contributed prompts is not mentioned in the blog post or anywhere in the repo.

**Comment by rabwill** [comment]
Good point, we will definitely add this in the repo @mjfusa thanks for the suggestion.

**Comment by rabwill** [comment]
Added to above suggestion to the readme : https://github.com/pnp/copilot-prompts?tab=readme-ov-file#copy-the-sample-json-file
